//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Events
    {
        public string Created_By { get; set; }
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
